[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# Erhöhe das Request-Body-Limit für Functions
[functions."*"]
  timeout = 30

# Erhöhe das Request-Body-Limit für Upload-Funktionen
[functions."admin-upload-file"]
  timeout = 60
  request_body_size = "100mb"

[functions."files-download"]
  timeout = 30
  request_body_size = "10mb"
